# Generated by Django 4.2.13 on 2024-07-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loginhistory',
        ),
    ]
