# Generated by Django 4.2.13 on 2024-07-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_loginhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
